### ISSUE TITLE
Design, build and launch page 12 - social media

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#16]
'Tell the world about your grant via social media'

**Comment by ChloeAlper** [comment]
Please see creative attached @stevekeene @TomSteinberg @mattandrews 

![12-tell-the-world-about-your-grant-via-social-media](https://cloud.githubusercontent.com/assets/27225981/25800694/454c6974-33e2-11e7-8e75-7c09c7663f2d.png)

**Comment by ChloeAlper** [comment]
Alternative hero image:
![12-tell-the-world-about-your-grant-via-social-media-2](https://cloud.githubusercontent.com/assets/27225981/25800872/fdf8ea56-33e2-11e7-805d-677efdf79b55.png)

**Comment by mattandrews** [comment]
I prefer the first one (that chap's face might be a bit enormous on larger screens!) personally :)

**Comment by mattandrews** [comment]
If you can send me the photos used here (the hero image and those three device photos) I can start building this for a demo tomorrow (even if it's going to change!).

**Comment by ChloeAlper** [comment]
The PSD – 12-tell-the-world-about-your-grant-via-social-media.psd – is just copying across to our Dropbox @mattandrews . Let me know if it's easier for me to crop the images.

**Comment by stevekeene** [comment]
Agree on the first image! It all looks nice and clear.

A couple of comments:

I think we had called this page "Tell the world about your grant via social media" rather than "Help with publicity".

The three things we're asking people to do here won't link to other further content. Do the boxes suggest they link to somewhere else?

**Comment by ChloeAlper** [comment]
Please see amended 'actions' section (two options) @stevekeene @TomSteinberg @mattandrews:
Please also note addition of language dropdown + sharing icons

![12-tell-the-world-about-your-grant-via-social-media-20170510](https://cloud.githubusercontent.com/assets/27225981/25910522/7d61e3da-35a8-11e7-9015-9bbd436a9297.png)
![12-tell-the-world-about-your-grant-via-social-media-20170510-2](https://cloud.githubusercontent.com/assets/27225981/25910524/8024f4f4-35a8-11e7-9037-e8cc3d00e896.png)

**Comment by TomSteinberg** [comment]
Thanks Chloe! I think the version where the text is not placed in coloured blocks probably reads more easily.

Unless there are really pressing reasons to, is it possible to delay the implementation of both the social media buttons and the language switcher in the page header?

My main reason for asking is a) to keep building & testing time down b) because both page elements are actually ones we should look at through a 'designing with data' lens. We should read a bunch of recent research on the actual usage of sharing buttons, for example, before adding them back in.

**Comment by ChloeAlper** [comment]
That makes sense. I think @mattandrews might have a comment on the language dropdown (we spoke about it briefly on Tuesday and it sounds like we might need it), but for now here is a version without social links or language dropdown:

![12-tell-the-world-about-your-grant-via-social-media-20170511](https://cloud.githubusercontent.com/assets/27225981/25938398/f2750494-3626-11e7-9f87-3ed35ec07093.png)

**Comment by mattandrews** [comment]
My only concern with the language dropdown is that without it (or some version of it), how do we expose that there's a Welsh version of the page available? At the moment the only way you'll be able to find them is to enter via the existing site, choose the Welsh option, then navigate to one of our new pages.

**Comment by ChloeAlper** [comment]
Language dropdown added:
![12-tell-the-world-about-your-grant-via-social-media-20170511-2](https://cloud.githubusercontent.com/assets/27225981/25940855/64f5cb68-362f-11e7-984d-e04a06f9b8ea.png)

**Comment by ChloeAlper** [comment]
Welsh version attached: 
![12-tell-the-world-about-your-grant-via-social-media-20170511-2](https://cloud.githubusercontent.com/assets/27225981/25943227/1ea447cc-3637-11e7-9ba8-3aace45848b8.png)

**Comment by ChloeAlper** [comment]
Welsh logo added to header:
![12-tell-the-world-about-your-grant-via-social-media-welsh-logo](https://cloud.githubusercontent.com/assets/27225981/25953591/c8f8909c-365b-11e7-8b64-3612c524539d.png)

**Comment by TomSteinberg** [comment]
Officially the first new page on the Big Lottery Fund's new website. WCAG tested, browser tested, bilingual, high contrast style-sheet option. 

Nice work @ChloeAlper @mattandrews @stevekeene 

🛳
