### ISSUE TITLE
Design build & launch mobile navigation

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#20]

**Comment by ChloeAlper** [comment]
Two options. I've put them in situ to give you a rough idea of what you would see. I like the blue option best, how about you @mattandrews @TomSteinberg @stevekeene 

![mobile-navigation-opt-2-20170504](https://cloud.githubusercontent.com/assets/27225981/25708372/36f2a26e-30de-11e7-833d-edfce0e41421.png)


![mobile-navigation-opt-1-20170504](https://cloud.githubusercontent.com/assets/27225981/25708376/39f55786-30de-11e7-825b-3621d38922a6.png)

**Comment by mattandrews** [comment]
Think I prefer the blue, but it might just be because of the dividing lines between each link, which make it feel more navigation-y?

Also, does this mean that clicking the menu button will shift everything a few hundred pixels to the left? eg. the nav comes in from the right, but the page content itself shifts to accommodate it too?

**Comment by ChloeAlper** [comment]
@mattandrews that was the idea, yes. Do please suggest improvements if you think of any though

**Comment by stevekeene** [comment]
Change request: Make the links in the menu/header different.

Instead of Before you apply/Apply/About/Search

Change to Home/Funding/About/Search

These should link to:
Home: https://www.biglotteryfund.org.uk
Funding: https://www.biglotteryfund.org.uk/funding
About: https://www.biglotteryfund.org.uk/about-big
Search: https://www.biglotteryfund.org.uk/search?lang=en-GB&amp;q=&amp;type=All&amp;order=r

Explanation: We already using multiple titles for single pages, and adding more terminology now might just confuse things further. This will also buy us more time to consider what the future navigation should look like, and avoid any possible alarm from colleagues regarding a new site structure!
