### ISSUE TITLE
Choose browser testing solution and start to use

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#200]

**Comment by davidrapson** [comment]
I've put together a quick summary of our analytics data to inform this decision: https://docs.google.com/document/d/1S3xDuSy5i56RsAVt3UYpv3dgbCoyHVVCV4FVpHxxesI/edit#

In summary, based on the data rather than looking into a testing service we're better off getting our hands on a range of iPhones and an iPad to supplement our testing.

**Comment by davidrapson** [comment]
Based on the data mentioned above and after discussion with @mattandrews we're going to take the following approach in lieu of an external testing service. We should aim to test physically on the following device combinations that match the majority of our users

- Chrome on Windows (via workstations)
- Internet Explorer 11 (via workstations)
- iPhone 6
- iPhone 5 or SE
- iPhone 4
- iPad and/or iPad Mini
- Chrome on Android using Samsung Galaxy S6/S7
- Edge on Windows (via workstations)

The desktop browsers can be covered by a combination of workstations and virtual machines during development.

For mobile devices, I've spoken to Sue Killick in IT and they have a single iPhone and iPad for testing which can be requested from them when we need it.

However as these are only two devices which require us to book/request them each time we'd like to test on them it might instead be worth looking at getting budget to by 3 or 4 test devices for the team instead of relying on a single pair of shared devices.
