### ISSUE TITLE
Review how job roles are published.

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#580]
If there are more frequent requests to publish job postings (like https://github.com/biglotteryfund/blf-alpha/pull/578) we should revisit how they are handled.

The current process requires code changes and full application deployments. Given these are little bits of copy it's overkill and a good candidate to come from the CMS.

**Comment by mattandrews** [comment]
Was thinking about this and wondering what value we're adding by duplicating the existing (external) job listings. It's more work for HR to remove jobs from that page and then remember to ask us to remove them from the website too.

Maybe we should see if the third party service has an API or RSS feed etc and see if we can use that rather than duplicating the data?

**Comment by mattandrews** [comment]
Contacted HR today to see if we have any contacts with the third party to chat to about this.

**Comment by mattandrews** [comment]
Heard nothing back so have contacted the third party directly to see if they have any data feeds we could use for this.

**Comment by davidrapson** [comment]
The immediate concern for this ticket was that it required a deploy just to update a job role. Now that the jobs page lives in the CMS this is less of an issue. The data feed idea is great, but we can probably raise a new ticket if/when we want to try that.
