### ISSUE TITLE
Remove repetition of 'your' on order form section of page (3)

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#63]
Make the order form section easier to scan by removing repeated use of word 'Your' in the entry fields
![screen shot 2017-05-25 at 08 37 22](https://cloud.githubusercontent.com/assets/27225981/26440733/938b7d82-4125-11e7-942f-85d845306e60.png)

**Comment by mattandrews** [comment]
Fixed in https://github.com/biglotteryfund/blf-alpha/commit/28033b4c11a9b339298843173e909831f7adef19 and deployed to [production](https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials):

![image](https://cloud.githubusercontent.com/assets/394376/26442587/140db0d6-412d-11e7-8b91-114d62e98cdf.png)

(I didn't change the Welsh because I'm not 100% sure on the grammar and our valiant translator is off all week – we can pick this up when he's back!)
