### ISSUE TITLE
Ready CMS for wider usage by colleagues

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#694]
### Major tasks

- [x] Launch preview mode (https://github.com/biglotteryfund/blf-alpha/issues/701)
- [x] Improve translation workflow
- [x] Improve and/or automate image compression for hero images from the CMS.

### Formatting considerations

- [x] How to add anchor links?
- [x] Formatting of inline images (crops / max-widths etc.)
- [x] Review how documents are uploaded and managed
- [x] How to format buttons without needing to edit HTML (https://github.com/biglotteryfund/craft-dev/pull/50)
- [x] `width` attributes are stripped from images
- [x] `&nbsp;` is preserved and does weird things to linebreaks

**Comment by mattandrews** [comment]
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/585
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/580
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/539
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/537
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/530
- [ ] https://github.com/biglotteryfund/blf-alpha/issues/317

**Comment by mattandrews** [comment]
Re: anchor links – https://craftcms.stackexchange.com/a/13343

Basically, our links are hardcoded to simply `#section-3` etc (which is generated by the frontend app, so Craft doesn't know about them). We could use Craft's entry linking tool but this would still involve someone manually typing an anchor ID onto the entry URL (in the correct place, otherwise it'll break). 

Looks to me like our current solution is still the best, for now.

**Comment by mattandrews** [comment]
And on the `&nbsp;` issue, some notes here: https://craftcms.stackexchange.com/questions/5230/rich-text-field-adding-nbsp-and-normal-space-char-at-random

**Comment by mattandrews** [comment]
CMS access now granted to David Symons and Nic Hogg.
